[{if $oDetailsProduct->oxarticles__oxunitquantity->value}]
    [{oxmultilang ident="DETAILS_ARTWEIGHT" suffix="COLON"}]
        [{if $oDetailsProduct->oxarticles__oxunitname->value  == '_UNIT_KG'}]
            [{$oDetailsProduct->getMarmUnitPrice()*1000}] [{oxmultilang ident="G"}]
        [{elseif $oDetailsProduct->oxarticles__oxunitname->value  == '_UNIT_L'}]
            [{$oDetailsProduct->getMarmUnitPrice()*1000}] [{oxmultilang ident="ML"}]
        [{else}]
            [{$oDetailsProduct->getMarmUnitPrice()}]
        [{/if}]
[{else}]
    [{oxmultilang ident="DETAILS_ARTWEIGHT" suffix="COLON"}] [{$oDetailsProduct->oxarticles__oxweight->value*1000}] [{oxmultilang ident="G"}]
[{/if}]